* Testing
  Running tests for this program was not difficult. The only thing to ensure was that the expected output would occur given commands and options. I simply ran commands in bash to test their output, and then ensured that they had the same output when run from myshell. For each case, builtin commands would need to be tested as well as external binaries. The calling process for each is different, so they had to be tested separately. Then I would need to test that running scripts would execute the same as a the shell interface, so I would just run commands in the interface, and so long as the output was the same as when those commands were in a text file, the program was functioning properly.
  For testing IO redirection, "echo" and "wc" were useful, as they allowed easy and predictable writing to files, and echo is a builtin command, while cat is external. something like "echo hello | wc -w" was easily predictable, and so long as the output is the number of words, 1, the program was functioning. I could also "breakdown" the pipeline, by using "echo hello > file" and then "wc -w < file" to get the exact same output.
  GDB was used extensively to test parameters and inputs throughout the process, until they reflected exactly what they should.
  
